DROP TABLE IF EXISTS tariffs;
DROP TABLE IF EXISTS readings;
DROP TABLE IF EXISTS meter_registers;
DROP TABLE IF EXISTS meters;
DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS addresses;
DROP TABLE IF EXISTS services;